global:
  scrape_interval: 8s
  evaluation_interval: 8s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "spring_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["spring-app-container:8080"] #localhost or spring-app-container
    basic_auth:
      username: "prom_user"
      password: "prom_pass"
